# Generated by Django 4.2.4 on 2023-09-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='tiny_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
