# Generated by Django 4.2.4 on 2023-09-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_alter_url_tiny_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='tiny_url',
            field=models.CharField(max_length=255),
        ),
    ]
